### ISSUE TITLE
[BUG] Error when installing packages

### ISSUE THREAD

**Issue by Iamafnan** [vuki656/package-info.nvim#106]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

NVIM 0.7.0-dev

### Branch

master

### Actual behavior

It gives this error after then new nui.nvim update
![IMG_20211230_081406](https://user-images.githubusercontent.com/80388154/147717468-8c3a873d-ca3c-4c44-9a34-a9668248d3be.jpg)

### Expected behavior

It will open the nui component

### Steps to reproduce

- Update nui.nvim
- Try installing any package 

### Package info config

```lua
require('package-info').setup{ package_manager = "yarn" }
```

### Other information

It occurs after the nui.nvim update maybe nui's API is now changed

### Help

Yes

### Implementation help

I would help in the nui's issue and the yarn v1 support after this nui's issue

**Comment by vuki656** [comment]
It seems to be an upstream issue so I opened an [issue in NUI](https://github.com/MunifTanjim/nui.nvim/issues/85) repo to track it. 

As for yarn 1 support, I plan to implement it myself in a few days since I'm not home at the moment. Feel free to send a PR if you'd like to have it sooner.

What needs to be done in a nutshell is

1. Detect yarn 1 or 2> [here](https://github.com/vuki656/package-info.nvim/blob/fad6afade384ccadcfd0e08f07a022eee6eaae28/lua/package-info/config.lua#L67) and add another package manager type [here](https://github.com/vuki656/package-info.nvim/blob/fad6afade384ccadcfd0e08f07a022eee6eaae28/lua/package-info/constants.lua#L10) yarn1 and yarn2, not sure on the naming yet, we just need to distinguish between yarn 1 and yarn 2> 
2. Add another check [here](https://github.com/vuki656/package-info.nvim/blob/fad6afade384ccadcfd0e08f07a022eee6eaae28/lua/package-info/utils.lua#L127) to use a corresponding command.

**Comment by vuki656** [comment]
Fixed in [NUI](https://github.com/MunifTanjim/nui.nvim/commit/76fc8edf771adff74aba513bd0f62e984996ef88)
