### ISSUE TITLE
Figure out why on_stdout is being called twice

### ISSUE THREAD

**Issue by vuki656** [vuki656/package-info.nvim#19]
Currently `on_stdout` is being called twice and the second result is empty thus clearing the initial result.

It's fixed with a hack that stops it from running after the first run but there is probably a cleaner solution. 

I'm not too sure why this is happening, need to investigate.

**Comment by jose-elias-alvarez** [comment]
I'm not too familar with `jobstart`, but based on my experience with the equivalent `luv` functionality, I think what's going on is that `on_stdout` will get called once for each chunk, then return a table containing an empty string to indicate that there's no more output. If that's right, the correct approach would be to continue reading from `stdout` until it's empty, then parse the output. 

Great plugin by the way! Looking forward to the ability to install / upgrade packages directly, which will be a game-changer. Let me know if I can help in any way.

**Comment by vuki656** [comment]
Thanks!

Interesting, thanks for the feedback. Which approach do you use to call commands? I pretty much just need to call `npm outdated --json` and get the result from that. Is there a simpler/smarter way?

I just finished deleting feature on the `develop` branch if you'd like to check it out. Pretty much put your cursor on a line that has a dependency, call a command, it opens a popup to confirm the action, if yes deletes it and reloads the buffer.

**Comment by jose-elias-alvarez** [comment]
I think `jobstart` is the perfect solution for a simple case like this, since `vim.loop.spawn` (which is what null-ls uses) is flexible but requires a lot of boilerplate. [The documentation](https://neovim.io/doc/user/channel.html#channel-callback) for `jobstart` callbacks explains what's going on with `stdout` better than I can. 

I just tried out the `delete` functionality and it's looking great – keep up the good work!

**Comment by vuki656** [comment]
Awesome, thanks for the feedback. 

Now that I get how `jobstart` works, I'll get around fixing it soon.
