### ISSUE TITLE
[FEATURE REQUEST] Support for `pnpm`

### ISSUE THREAD

**Issue by xeho91** [vuki656/package-info.nvim#76]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Support for [`pnpm`].

[`pnpm`]: https://pnpm.io/

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

This plugin automatically detects `npm` and `yarn`.

I would like to help to contribute to add support for the `pnpm`.

**Comment by vuki656** [comment]
Hey, thanks for the suggestion,

currently, for both `yarn` and `npm`, `npm outdated` is being run since the output is the same.

I see that `pnpm` also has outdated cli command so you could probably add another detection method for `pnpm`, and based on that run `pnpm outdated --json` and just make sure it arrives in the same JSON format as currently expected.

- [Here](https://github.com/vuki656/package-info.nvim/blob/7f5d4f8583de1eaf1ae998c369cb1c81565205d7/lua/package-info/config.lua#L67) is the package manager detection 
- [Here](https://github.com/vuki656/package-info.nvim/blob/7f5d4f8583de1eaf1ae998c369cb1c81565205d7/lua/package-info/modules/core.lua#L19) is the cli call. You would run `pnpm outdated --json` here, just make sure the output format is the same as for `npm`

Let me know if you need more info to get started.

**Comment by xeho91** [comment]
> Hey, thanks for the suggestion,
> 
> currently, for both `yarn` and `npm`, `npm outdated` is being run since the output is the same.
> 
> I see that `pnpm` also has outdated cli command so you could probably add another detection method for `pnpm`, and based on that run `pnpm outdated --json` and just make sure it arrives in the same JSON format as currently expected.
> 
>     * [Here](https://github.com/vuki656/package-info.nvim/blob/7f5d4f8583de1eaf1ae998c369cb1c81565205d7/lua/package-info/config.lua#L67) is the package manager detection
> 
>     * [Here](https://github.com/vuki656/package-info.nvim/blob/7f5d4f8583de1eaf1ae998c369cb1c81565205d7/lua/package-info/modules/core.lua#L19) is the cli call. You would run `pnpm outdated --json` here, just make sure the output format is the same as for `npm`
> 
> 
> Let me know if you need more info to get started.

Thank you!

I'll start working on it on the upcoming weekend :)

**Comment by mtoohey31** [comment]
I'm interested in helping too, not sure if you've gotten started. It looks like pnpm doesn't support `--json` for `outdated`, but we can just use `npm` as well. [Here's the link](https://github.com/pnpm/pnpm/issues/2705) to the relevant issue at pnpm's repos though, if this is resolved we might want to do it with pnpm in case it can do things faster, when it's supported.
