### ISSUE TITLE
[BUG] The plugin adds to the vim undo history

### ISSUE THREAD

**Issue by aMOPel** [vuki656/package-info.nvim#83]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

NVIM v0.6.0-dev

### Branch

master

### Actual behavior

When using the `.show()` function, a bunch of entries are added to the undo history.

### Expected behavior

No changes to the undo history are done by the `.show()` function.

### Steps to reproduce

1. Make an edit in the `package.json`
2. Invoke `.show()`
3. Press `u` and see how it doesn't immediately undo 1. (the number of added changes varies, and i don't know on what they depend)

### Package info config

nothing

### Other information

Really nice plugin :)

### Help

No, sorry.

**Comment by vuki656** [comment]
Will look into it. Likely because of the buffer reloading or stuff that is being done after the change.

**Comment by vuki656** [comment]
Hey, I just tested it and it seems that invoking `:e` will add a step to the undo history. I don't think this is avoidable since the buffer needs to be reloaded after the virtual text update and or when you `delete/upgrade/install` a package.

Let me know if you have any potential solutions to this otherwise I'll have to close it unfortunately since the plugin can't work without that functionality.

**Comment by aMOPel** [comment]
Bummer
